# -*- coding: utf-8 -*-
"""aspect_sentiment_summary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qANy1PPPPWAH-M6iKCrn9EmEjbqWiBAt
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Read sentiment analysis data
sentiment_df = pd.read_csv("/content/drive/My Drive/sentiment_analysis_2023.csv")

# Read aspect frequency data
aspect_frequency_df = pd.read_csv("/content/drive/My Drive/aspect_frequency_filtered.csv")

# Initialize dictionaries to store information for each aspect
aspect_data = {}

# Iterate over each row in the sentiment analysis data
for index, row in sentiment_df.iterrows():
    # Extract sentiment results from the comment
    sentiment_results = eval(row['SentimentResults'])
    for aspect, sentiment_value in sentiment_results.items():
        # Check if the aspect is in the aspect frequency data
        if aspect in aspect_frequency_df['Aspect'].values:
            # Get the sentiment score
            sentiment_score = sentiment_value[0] - sentiment_value[1]
            # Initialize or update the aspect data
            if aspect not in aspect_data:
                aspect_data[aspect] = {
                    'Total Reviews': 1,
                    'Positive Reviews': sentiment_value[0],
                    'Negative Reviews': sentiment_value[1],
                    'Positive Sentiment Sum': sentiment_score if sentiment_score > 0 else 0,
                    'Negative Sentiment Sum': abs(sentiment_score) if sentiment_score < 0 else 0
                }
            else:
                aspect_data[aspect]['Total Reviews'] += 1
                aspect_data[aspect]['Positive Reviews'] += sentiment_value[0]
                aspect_data[aspect]['Negative Reviews'] += sentiment_value[1]
                aspect_data[aspect]['Positive Sentiment Sum'] += sentiment_score if sentiment_score > 0 else 0
                aspect_data[aspect]['Negative Sentiment Sum'] += abs(sentiment_score) if sentiment_score < 0 else 0

# Calculate average positive sentiment and average negative sentiment for each aspect
for aspect, data in aspect_data.items():
    data['Average Positive Sentiment'] = data['Positive Sentiment Sum'] / data['Total Reviews'] if data['Total Reviews'] > 0 else 0
    data['Average Negative Sentiment'] = data['Negative Sentiment Sum'] / data['Total Reviews'] if data['Total Reviews'] > 0 else 0

# Create DataFrame from aspect data
aspect_df = pd.DataFrame.from_dict(aspect_data, orient='index')

# Save DataFrame to CSV
aspect_df.to_csv('/content/drive/My Drive/aspect_sentiment_summary.csv')

print("Aspect sentiment summary saved successfully!")